;; extends

; (("class" @keyword) (#set! conceal "cls"))
; (("assert" @keyword) (#set! conceal "?"))
; (("import" @include) (#set! conceal "i"))
; ((import_from_statement ("from") @include) (#set! conceal "<="))
; ((yield ("from") @keyword) (#set! conceal "<"))
; ((call function: (identifier) @function.builtin (#eq? @function.builtin "print")) (#set! conceal "p"))
; (("and" @keyword.operator) (#set! conceal "&&"))
; (("break" @keyword) (#set! conceal "brk"))
; ;(("with" @keyword) (#set! conceal "w"))
; (("pass" @keyword) (#set! conceal "P"))
; (("yield" @keyword) (#set! conceal "Y"))
; ; (("for" @repeat) (#set! conceal "F"))
; (("elif" @conditional) (#set! conceal "ei"))
; (("lambda" @include) (#set! conceal "λ"))
; (("if" @conditional) (#set! conceal "?"))
; (("not" @keyword.operator) (#set! conceal "!"))
; (("or" @keyword.operator) (#set! conceal "||"))
; (("continue" @keyword) (#set! conceal "C"))
; (("return" @keyword) (#set! conceal "ret"))
; (("del" @keyword) (#set! conceal "D"))
; (("else" @conditional) (#set! conceal "e"))
; (("while" @repeat) (#set! conceal "W"))
; (("global" @keyword) (#set! conceal "G"))
; (("def" @keyword.function) (#set! conceal "func"))
