# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !

# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

if [ $(uname) = "FreeBSD" ]; then
    alias l='ls -lG'
    alias ll='ls -laG'
else
    alias l='ls --group-directories-first -l'
    alias ll='ls --group-directories-first -la'
fi

alias mv='mv -i'
alias cp='cp --reflink=always -i'
alias rm='rm -i'

alias cd...='cd ../..'
alias cd..='cd ..'
alias cd.='cd .'
alias cd~='cd ~'
alias ...='cd ../..'
alias ..='cd ..'
alias ~='cd ~'

alias t='task'

# Put your fun stuff here.

export HISTCONTROL=ignoreboth
